/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#00163a",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#006b5f",
          foreground: "#ffffff",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Stitch "dossier" palette
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#455e91",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#aec6ff",
        "on-surface": "#191c1e",
        "on-surface-variant": "#44474f",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#2c4678",
        "on-primary-container": "#7a93ca",
        "primary-container": "#0b2a5b",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#aec6ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006f64",
        "on-secondary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#005048",
        "secondary-container": "#6df5e1",
        "secondary-fixed": "#71f8e4",
        "secondary-fixed-dim": "#4fdbc8",
        "tertiary": "#2c0f00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4b1f00",
        "on-tertiary-container": "#c8835a",
        "tertiary-fixed": "#ffdbc9",
        "tertiary-fixed-dim": "#ffb68c",
        "on-tertiary-fixed": "#321200",
        "on-tertiary-fixed-variant": "#6d3916",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "outline": "#747780",
        "outline-variant": "#c4c6d0",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        dossier: "0 8px 30px rgba(0, 22, 58, 0.04)",
        ambient: "0 32px 32px -16px rgba(0, 22, 58, 0.04)",
        nav: "0 4px 20px -4px rgba(11, 42, 91, 0.05)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
