# Generated by Django 5.0.8 on 2026-04-20 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="labs/logos/")),
                (
                    "letterhead_header",
                    models.ImageField(blank=True, null=True, upload_to="labs/letterheads/"),
                ),
                (
                    "letterhead_footer",
                    models.ImageField(blank=True, null=True, upload_to="labs/letterheads/"),
                ),
                ("primary_color", models.CharField(default="#1d4ed8", max_length=7)),
                ("secondary_color", models.CharField(default="#0ea5e9", max_length=7)),
                (
                    "default_signature",
                    models.ImageField(blank=True, null=True, upload_to="labs/signatures/"),
                ),
                (
                    "tax_registration",
                    models.CharField(blank=True, help_text="GST number", max_length=50),
                ),
                (
                    "accreditation_info",
                    models.TextField(blank=True, help_text="NABL details, etc."),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("subscription_started_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_expires_at", models.DateTimeField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("price_monthly", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("price_yearly", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("max_reports_per_month", models.PositiveIntegerField(blank=True, null=True)),
                ("max_users", models.PositiveIntegerField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="tenancy.lab",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lab branches",
                "ordering": ("lab", "name"),
            },
        ),
        migrations.AddField(
            model_name="lab",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labs",
                to="tenancy.subscriptionplan",
            ),
        ),
    ]
