# Generated by Django 5.0.8 on 2026-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="phone",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="labbranch",
            name="phone",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
