# Generated by Django 5.0.8 on 2026-04-20 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "sample_type",
                    models.CharField(blank=True, help_text="e.g. Whole Blood EDTA", max_length=100),
                ),
                ("method", models.CharField(blank=True, max_length=200)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("turnaround_time_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "loinc_code",
                    models.CharField(
                        blank=True, help_text="For analyzer integration", max_length=50
                    ),
                ),
                ("is_calculated", models.BooleanField(default=False)),
                ("calculation_formula", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("clinical_significance", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="tenancy.lab",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ReferenceRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("A", "All")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("age_min_years", models.PositiveIntegerField(blank=True, null=True)),
                ("age_max_years", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "range_min",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "range_max",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "range_text",
                    models.CharField(
                        blank=True,
                        help_text="For non-numeric: 'Negative', 'Not Detected'",
                        max_length=200,
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "critical_high",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("unit_override", models.CharField(blank=True, max_length=50)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="catalog.test",
                    ),
                ),
            ],
            options={
                "ordering": ("test", "sex", "age_min_years"),
            },
        ),
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = system default, available to all labs.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_categories",
                        to="tenancy.lab",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "test categories",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="test",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tests",
                to="catalog.testcategory",
            ),
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "pdf_template_path",
                    models.CharField(blank=True, default="reports/generic.html", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="tenancy.lab",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="catalog.testcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("section", models.CharField(blank=True, max_length=100)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_tests",
                        to="catalog.reporttemplate",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_memberships",
                        to="catalog.test",
                    ),
                ),
            ],
            options={
                "ordering": ("template", "display_order"),
                "unique_together": {("template", "test")},
            },
        ),
        migrations.AddConstraint(
            model_name="testcategory",
            constraint=models.UniqueConstraint(
                fields=("lab", "code"), name="unique_category_code_per_lab"
            ),
        ),
        migrations.AddConstraint(
            model_name="test",
            constraint=models.UniqueConstraint(
                fields=("lab", "code"), name="unique_test_code_per_lab"
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplate",
            constraint=models.UniqueConstraint(
                fields=("lab", "code"), name="unique_template_code_per_lab"
            ),
        ),
    ]
