# Generated by Django 5.0.8 on 2026-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencerange",
            name="critical_high",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="referencerange",
            name="critical_low",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="referencerange",
            name="range_max",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="referencerange",
            name="range_min",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="pdf_template_path",
            field=models.CharField(blank=True, default="pdf/reports/generic.html", max_length=200),
        ),
    ]
