# Generated by Django 5.0.8 on 2026-05-06 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_package_prerequisite_tests"),
        ("tenancy", "0005_add_tech_reg_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "name_alt",
                    models.CharField(
                        blank=True, help_text="Optional alternate / Hindi name.", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("list_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offer_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = system default, available to all labs.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="tenancy.lab",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="PackageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_templates",
                        to="catalog.package",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_memberships",
                        to="catalog.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("package", "display_order"),
            },
        ),
        migrations.AddConstraint(
            model_name="package",
            constraint=models.UniqueConstraint(
                fields=("lab", "code"), name="unique_package_code_per_lab"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packagetemplate",
            unique_together={("package", "template")},
        ),
    ]
