# Generated by Django 5.0.8 on 2026-04-20 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("patient_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "age_unit",
                    models.CharField(
                        choices=[("years", "Years"), ("months", "Months"), ("days", "Days")],
                        default="years",
                        max_length=10,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("aadhaar_last_4", models.CharField(blank=True, max_length=4)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=200)),
                ("emergency_contact_phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.lab",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the patient registers for the portal and claims this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("spouse", "Spouse"),
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        default="self",
                        max_length=20,
                    ),
                ),
                (
                    "primary_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_linkages",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("data_processing", "Data processing"),
                            ("report_sharing", "Report sharing"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=40,
                    ),
                ),
                ("given_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("lab", "patient_code"), name="unique_patient_code_per_lab"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                fields=("lab", "phone"),
                name="unique_phone_per_lab",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="familymember",
            unique_together={("primary_user", "patient")},
        ),
    ]
