# Generated by Django 5.0.8 on 2026-05-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_package_packagetemplate_and_more"),
        ("reports", "0004_report_sample_collected_by_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, the report bundles multiple templates from this package.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="catalog.package",
            ),
        ),
    ]
